### ISSUE TITLE
Failed to generate Test scripts for 649453932_Chinese_Text_Classification_Pytorch.zip

### ISSUE THREAD

**Issue by DiweiSun** [jansel/pytorch-jit-paritybench#6]
Hi, 

I tried to generate Test Scripts for "649453932_Chinese_Text_Classification_Pytorch.zip" but it failed with Error as Below:
The script is like: python main.py -g ./649453932_Chinese_Text_Classification_Pytorch.zip --tests-dir ./

Is there anything I'm overlooking?

Error from subprocess
Traceback (most recent call last):
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/utils.py", line 51, in call_with_timeout_subproc
    result = fn(*args, *kwargs)
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/generate.py", line 42, in generate_zipfile_subproc
    extractor.main(path)
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/module_extractor.py", line 308, in main
    self.test_modules()
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/module_extractor.py", line 262, in test_modules
    self.test_nn_module(name, value)
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/module_extractor.py", line 281, in test_nn_module
    stats, errors, testcases = call_with_timeout(
  File "/home/pytorch/molly/paritytest/pytorch-jit-paritybench/paritybench/utils.py", line 26, in call_with_timeout
    proc.start()
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/pytorch/anaconda3/envs/torch20_parity/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'paritybench.module_extractor.output.Encoder'>: import of module 'paritybench.module_extractor.output' failed

**Comment by yanboliang** [comment]
@DiweiSun Can you try to comment out this line? It would fix this issue.
https://github.com/jansel/pytorch-jit-paritybench/blob/045c47959d9ca4729877c693c8f8e608ce6beb5c/paritybench/main.py#L72
I think this is because of the conflicts between Python multithread vs PyTorch multithread, we should only enable it during evaluation mode. I'll send a PR to fix it soon.

BTW, [this model](https://github.com/jansel/pytorch-jit-paritybench/blob/master/generated/test_649453932_Chinese_Text_Classification_Pytorch.py) is already available in this repro, you don't need to re-generate it again if you just want to use it.
